export const RECT_BATCH_FLOATS_PER_VERTEX = 6;
export const RECT_BATCH_VERTICES_PER_RECT = 6;
export const RECT_BATCH_INITIAL_CAPACITY_RECTS = 1024;
export const RECT_CHUNK_MAX_RECTS = 512;
export const RECT_BATCH_BYTES_PER_FLOAT = 4;
