import {
  armCornerRadiusOnPointerDown,
  armEllipseArcOnPointerDown,
  armEllipseArcRatioOnPointerDown,
  armEllipseArcRotateOnPointerDown,
  armGroupBoundsOnPointerDown,
  armHitOnPointerDown,
  armLineEndpointOnPointerDown,
  armMarqueeOnPointerDown,
  armPathOffsetOnPointerDown,
  armPolygonCornerRadiusOnPointerDown,
  armPolygonVertexCountOnPointerDown,
  armResizeOnPointerDown,
  armRotateOnPointerDown,
  armSelectedTextBoundsOnPointerDown,
  armStarCornerRadiusOnPointerDown,
  armStarVertexCountOnPointerDown,
  toggleSelectionOnPointerDown,
} from './armResolvers';

export const ARM_RESOLVERS = [
  armPathOffsetOnPointerDown,
  armPolygonVertexCountOnPointerDown,
  armStarVertexCountOnPointerDown,
  armEllipseArcOnPointerDown,
  armEllipseArcRotateOnPointerDown,
  armEllipseArcRatioOnPointerDown,
  armResizeOnPointerDown,
  armCornerRadiusOnPointerDown,
  armPolygonCornerRadiusOnPointerDown,
  armStarCornerRadiusOnPointerDown,
  armRotateOnPointerDown,
  armLineEndpointOnPointerDown,
  toggleSelectionOnPointerDown,
  armHitOnPointerDown,
  armSelectedTextBoundsOnPointerDown,
  armGroupBoundsOnPointerDown,
  armMarqueeOnPointerDown,
];
