export const DEFAULT_LAYOUT_GUIDE_COLOR = '#FF0000';
export const DEFAULT_LAYOUT_GUIDE_OPACITY = 10;
export const DEFAULT_LAYOUT_GUIDE_GRID_SIZE = 10;
export const DEFAULT_LAYOUT_GUIDE_COUNT = 5;
export const DEFAULT_LAYOUT_GUIDE_GUTTER = 20;
export const DEFAULT_LAYOUT_GUIDE_MARGIN = 0;
export const DEFAULT_LAYOUT_GUIDE_SECTION_SIZE = 100;
