// types
import { TCanvasRefs } from 'types/design/canvas/types';

export const createCanvasRefs = (overrides: Partial<TCanvasRefs> = {}): TCanvasRefs => ({
  canvasRef: { current: null },
  cornerRadiusDragRef: { current: null },
  draftRef: { current: null },
  ellipseArcDragRef: { current: null },
  ellipseArcRatioDragRef: { current: null },
  ellipseArcRotateDragRef: { current: null },
  hoverRef: { current: null },
  hoveredSegmentIdRef: { current: null },
  hoveredVectorEdgeInsertPointRef: { current: null },
  hoveredVectorHandleRef: { current: null },
  hoveredVectorSegmentIdRef: { current: null },
  hoveredVectorVertexIdRef: { current: null },
  marqueeRef: { current: null },
  penDragOriginRef: { current: null },
  penDraggedHandlePositionRef: { current: null },
  penHoveredDragArmableVertexRef: { current: false },
  penNewVertexPreviewRef: { current: null },
  penPreviewRef: { current: null },
  polygonCornerRadiusDragRef: { current: null },
  preVectorMarqueeSegmentIdsRef: { current: [] },
  preVectorMarqueeVertexIdsRef: { current: [] },
  rotateDragRef: { current: null },
  selectedVectorHandlesRef: { current: [] },
  selectedVectorSegmentIdsRef: { current: [] },
  selectedVectorVertexIdsRef: { current: [] },
  sliceRef: { current: null },
  starCornerRadiusDragRef: { current: null },
  vectorMultiSelectBoxRef: { current: null },
  vectorMultiSelectResizeDragRef: { current: null },
  vectorMultiSelectRotateDragRef: { current: null },
  ...overrides,
});
