// others
import { ERASER_DEFAULT_DIAMETER_PX } from 'constant/canvas';

// types
import { TCanvasRefs } from 'types/design/canvas/types';

export const createCanvasRefs = (overrides: Partial<TCanvasRefs> = {}): TCanvasRefs => ({
  canvasRef: { current: null },
  colorSampleRequestRef: { current: null },
  cornerRadiusDragRef: { current: null },
  draftRef: { current: null },
  draggedNodeIdsRef: { current: null },
  draggedVectorFillFacesRef: { current: null },
  draggedVectorNodeSnapshotsRef: { current: null },
  ellipseArcDragRef: { current: null },
  ellipseArcRatioDragRef: { current: null },
  ellipseArcRotateDragRef: { current: null },
  eraseBrushCenterRef: { current: null },
  eraserDiameterRef: { current: ERASER_DEFAULT_DIAMETER_PX },
  hoverRef: { current: null },
  hoveredSegmentIdRef: { current: null },
  hoveredVectorCutPointRef: { current: null },
  hoveredVectorCutSegmentRef: { current: null },
  hoveredVectorEdgeInsertPointRef: { current: null },
  hoveredVectorFaceSelectRef: { current: null },
  hoveredVectorHandleRef: { current: null },
  hoveredVectorPaintFaceKeyRef: { current: null },
  hoveredVectorSegmentIdRef: { current: null },
  hoveredVectorShapeBuilderFaceRef: { current: null },
  hoveredVectorVertexIdRef: { current: null },
  hoveredVectorWidthPointRef: { current: null },
  isVectorShapeBuilderBoxModeRef: { current: false },
  isVectorShapeBuilderSubtractRef: { current: false },
  lastVectorWidthHandleSideRef: { current: null },
  marqueeRef: { current: null },
  newVectorCutVertexIdsRef: { current: new Set() },
  penDragOriginRef: { current: null },
  penDraggedHandleIsSnappedRef: { current: false },
  penDraggedHandlePositionRef: { current: null },
  penHoveredDragArmableVertexRef: { current: false },
  penNewVertexPreviewRef: { current: null },
  penPreviewRef: { current: null },
  pencilPreviewPointsRef: { current: null },
  pencilRawPreviewPointsRef: { current: null },
  pencilShowRawPreviewRef: { current: false },
  polygonCornerRadiusDragRef: { current: null },
  preVectorMarqueeSegmentIdsRef: { current: [] },
  preVectorMarqueeVertexIdsRef: { current: [] },
  resizedNodeIdsRef: { current: null },
  resizedVectorNodeSnapshotsRef: { current: null },
  rotateDragRef: { current: null },
  rotatedNodeIdsRef: { current: null },
  rotatedVectorNodeSnapshotsRef: { current: null },
  selectedVectorHandlesRef: { current: [] },
  selectedVectorSegmentIdsRef: { current: [] },
  selectedVectorVertexIdsRef: { current: [] },
  selectedVectorWidthHandlesRef: { current: [] },
  sliceRef: { current: null },
  snappedVectorHandleRef: { current: null },
  starCornerRadiusDragRef: { current: null },
  touchedVectorCutVertexIdsRef: { current: new Set() },
  touchedVectorShapeBuilderFacesRef: { current: {} },
  vectorAlignmentGuideRef: { current: null },
  vectorCutPreviewRef: { current: null },
  vectorEraseStrokeRef: { current: null },
  vectorLassoPathRef: { current: null },
  vectorMultiDragRef: { current: null },
  vectorMultiSelectBoxRef: { current: null },
  vectorMultiSelectResizeDragRef: { current: null },
  vectorMultiSelectRotateDragRef: { current: null },
  vectorShapeBuilderPathRef: { current: null },
  vectorWidthPointDragRef: { current: null },
  ...overrides,
});
