export enum E2EAttribute {
  accordion = 'accordion',
  accordionItem = 'accordion-item',
  alignmentArea = 'alignment-area',
  buttonGroup = 'button-group',
  bypassGlobalShortcuts = 'bypass-global-shortcuts',
  checkbox = 'checkbox',
  checkboxInput = 'checkbox-input',
  componentHeader = 'component-header',
  scrubbableInput = 'scrubbable-input',
  section = 'section',
  textField = 'text-field',
  textFieldInput = 'text-field-input',
  toggleButtonGroup = 'toggle-button-group',
}
