export enum E2EAttribute {
  accordion = 'accordion',
  accordionItem = 'accordion-item',
  alignmentArea = 'alignment-area',
  buttonGroup = 'button-group',
  bypassGlobalShortcuts = 'bypass-global-shortcuts',
  checkbox = 'checkbox',
  checkboxInput = 'checkbox-input',
  componentHeader = 'component-header',
  gridArea = 'grid-area',
  gridCellInput = 'grid-cell-input',
  gridCellsInput = 'grid-cells-input',
  gridInputs = 'grid-inputs',
  gridSettingsOpen = 'grid-settings-open',
  gridSettingsPanel = 'grid-settings-panel',
  gridTrackRow = 'grid-track-row',
  gridTrackValue = 'grid-track-value',
  scrubbableInput = 'scrubbable-input',
  section = 'section',
  textField = 'text-field',
  textFieldInput = 'text-field-input',
  toggleButtonGroup = 'toggle-button-group',
}
