export enum KeyboardKeys {
  a = 'KeyA',
  alt = 'Alt',
  arrowDown = 'ArrowDown',
  arrowLeft = 'ArrowLeft',
  arrowRight = 'ArrowRight',
  arrowUp = 'ArrowUp',
  b = 'KeyB',
  backslash = 'Backslash',
  backspace = 'Backspace',
  bracketLeft = 'BracketLeft',
  bracketRight = 'BracketRight',
  c = 'KeyC',
  control = 'Control',
  d = 'KeyD',
  delete = 'Delete',
  digit0 = 'Digit0',
  digit1 = 'Digit1',
  digit2 = 'Digit2',
  e = 'KeyE',
  enter = 'Enter',
  escape = 'Escape',
  f = 'KeyF',
  g = 'KeyG',
  h = 'KeyH',
  k = 'KeyK',
  l = 'KeyL',
  m = 'KeyM',
  minus = 'Minus',
  n = 'KeyN',
  numpadAdd = 'NumpadAdd',
  numpadSubtract = 'NumpadSubtract',
  o = 'KeyO',
  p = 'KeyP',
  plus = 'Equal',
  q = 'KeyQ',
  r = 'KeyR',
  s = 'KeyS',
  shift = 'Shift',
  t = 'KeyT',
  v = 'KeyV',
  w = 'KeyW',
  x = 'KeyX',
  z = 'KeyZ',
}

export enum MouseButton {
  middle = 1,
  primary = 0,
}
