export enum KeyboardKeys {
  '+' = '+',
  '-' = '-',
  alt = 'Alt',
  b = 'KeyB',
  backspace = 'Backspace',
  c = 'KeyC',
  control = 'Control',
  d = 'KeyD',
  delete = 'Delete',
  enter = 'Enter',
  escape = 'Escape',
  f = 'KeyF',
  h = 'KeyH',
  k = 'KeyK',
  l = 'KeyL',
  o = 'KeyO',
  p = 'KeyP',
  q = 'KeyQ',
  r = 'KeyR',
  s = 'KeyS',
  shift = 'Shift',
  t = 'KeyT',
  v = 'KeyV',
  x = 'KeyX',
  z = 'KeyZ',
}

export enum MouseButton {
  middle = 1,
  primary = 0,
}
