export const STROKE_BRUSH_PICKER_WIDTH_PX = 240;
export const STROKE_BRUSH_PICKER_HEIGHT_PX = 510;
export const STROKE_BRUSH_CATEGORY_HEADER_HEIGHT_PX = 32;
export const STROKE_BRUSH_OPTION_HEIGHT_PX = 68;
export const STROKE_BRUSH_OPTION_HEADER_HEIGHT_PX = 24;
