// others
import { ALT, CONTROL, SHIFT } from 'constant/mainKeys';

// types
import { TKeyboardShortcuts } from './types';
import { ToolName } from 'types/design/enums';

export const KEYBOARD_SHORTCUTS: TKeyboardShortcuts = {
  addAutoLayout: [SHIFT, 'A'],
  annotations: [SHIFT, 'Y'],
  [ToolName.arrow]: [SHIFT, 'L'],
  bringToFront: [']'],
  collapseLayers: [ALT, 'L'],
  [ToolName.comment]: ['C'],
  comments: [SHIFT, 'C'],
  copy: [CONTROL, 'C'],
  copyAsPng: [SHIFT, CONTROL, 'C'],
  copyProperties: [ALT, CONTROL, 'C'],
  createComponent: [ALT, CONTROL, 'K'],
  [ToolName.cut]: ['X'],
  [ToolName.default]: ['V'],
  delete: ['⌫'],
  duplicate: [CONTROL, 'D'],
  [ToolName.ellipse]: ['O'],
  [ToolName.erase]: [SHIFT, 'E'],
  export: [SHIFT, CONTROL, 'E'],
  find: [CONTROL, 'F'],
  findNext: [SHIFT, CONTROL, 'F'],
  findNextFrame: ['End'],
  findPrevious: [SHIFT, CONTROL, 'D'],
  findPreviousFrame: ['Home'],
  flatten: [ALT, SHIFT, 'F'],
  flipHorizontal: [SHIFT, 'H'],
  flipVertical: [SHIFT, 'V'],
  [ToolName.frame]: ['F'],
  frameSelection: [ALT, CONTROL, 'G'],
  groupSelection: [CONTROL, 'G'],
  [ToolName.hand]: ['H'],
  hideShowLayer: [SHIFT, CONTROL, 'H'],
  [ToolName.lasso]: ['Q'],
  layoutGuides: [SHIFT, 'G'],
  [ToolName.line]: ['L'],
  lockUnlockLayer: [SHIFT, CONTROL, 'L'],
  [ToolName.media]: [CONTROL, SHIFT, 'K'],
  multiplayerCursors: [ALT, CONTROL, '\\'],
  nextPage: ['↓'],
  openActions: [CONTROL, 'K'],
  openDesignPanel: [ALT, '8'],
  openLayersPanel: [ALT, '1'],
  openLibrariesPanel: [ALT, '2'],
  openPrototypePanel: [ALT, '9'],
  outlineStroke: [ALT, CONTROL, 'O'],
  [ToolName.paint]: [SHIFT, 'B'],
  pasteOverSelection: [SHIFT, CONTROL, 'V'],
  pasteProperties: [ALT, CONTROL, 'V'],
  pasteToReplace: [SHIFT, CONTROL, 'R'],
  [ToolName.pen]: ['P'],
  [ToolName.pencil]: [SHIFT, 'P'],
  pixelGrid: [SHIFT, "'"],
  pixelPreview: [SHIFT, CONTROL, 'P'],
  placeImage: [SHIFT, CONTROL, 'K'],
  [ToolName.polygon]: [],
  previousPage: ['↑'],
  [ToolName.rectangle]: ['R'],
  redo: [SHIFT, CONTROL, 'Z'],
  renameLayer: [CONTROL, 'R'],
  rulers: [SHIFT, 'R'],
  saveToVersionHistory: [ALT, CONTROL, 'S'],
  [ToolName.scale]: ['K'],
  [ToolName.section]: [SHIFT, 'S'],
  selectAll: [CONTROL, 'A'],
  selectInverse: [SHIFT, CONTROL, 'A'],
  selectMatchingLayers: [ALT, CONTROL, 'A'],
  selectNone: ['↺'],
  sendToBack: ['['],
  showHideUi: [CONTROL, '\\'],
  showOutlines: [SHIFT, CONTROL, 'O'],
  [ToolName.slice]: ['S'],
  [ToolName.star]: [],
  switchToDevMode: [SHIFT, 'D'],
  [ToolName.text]: ['T'],
  [ToolName.textOnPath]: [],
  toggleUiMinimized: [SHIFT, CONTROL, '\\'],
  undo: [CONTROL, 'Z'],
  zoomIn: [CONTROL, '+'],
  zoomOut: [CONTROL, '-'],
  zoomTo100: [CONTROL, '0'],
  zoomToFit: [SHIFT, '1'],
  zoomToNextFrame: ['N'],
  zoomToPreviousFrame: [SHIFT, 'N'],
  zoomToSelection: [SHIFT, '2'],
};
