// others
import { ALT, CONTROL, SHIFT } from 'constant/mainKeys';

// types
import { TKeyboardShortcuts } from './types';
import { ToolName } from 'types/design/enums';

export const KEYBOARD_SHORTCUTS: TKeyboardShortcuts = {
  addAutoLayout: [SHIFT, 'A'],
  [ToolName.arrow]: [SHIFT, 'L'],
  bringToFront: [']'],
  collapseLayers: [ALT, 'L'],
  [ToolName.comment]: ['C'],
  copy: [CONTROL, 'C'],
  copyAsPng: [SHIFT, CONTROL, 'C'],
  copyProperties: [ALT, CONTROL, 'C'],
  createComponent: [ALT, CONTROL, 'K'],
  [ToolName.cut]: ['X'],
  [ToolName.default]: ['V'],
  delete: ['⌫'],
  duplicate: [CONTROL, 'D'],
  [ToolName.ellipse]: ['O'],
  [ToolName.erase]: [SHIFT, 'E'],
  export: [SHIFT, CONTROL, 'E'],
  find: [CONTROL, 'F'],
  findNext: [SHIFT, CONTROL, 'F'],
  findPrevious: [SHIFT, CONTROL, 'D'],
  flatten: [ALT, SHIFT, 'F'],
  flipHorizontal: [SHIFT, 'H'],
  flipVertical: [SHIFT, 'V'],
  [ToolName.frame]: ['F'],
  frameSelection: [ALT, CONTROL, 'G'],
  groupSelection: [CONTROL, 'G'],
  [ToolName.hand]: ['H'],
  hideShowLayer: [SHIFT, CONTROL, 'H'],
  [ToolName.lasso]: ['Q'],
  [ToolName.line]: ['L'],
  lockUnlockLayer: [SHIFT, CONTROL, 'L'],
  [ToolName.media]: [CONTROL, SHIFT, 'K'],
  openActions: [CONTROL, 'K'],
  outlineStroke: [ALT, CONTROL, 'O'],
  [ToolName.paint]: [SHIFT, 'B'],
  pasteOverSelection: [SHIFT, CONTROL, 'V'],
  pasteProperties: [ALT, CONTROL, 'V'],
  pasteToReplace: [SHIFT, CONTROL, 'R'],
  [ToolName.pen]: ['P'],
  [ToolName.pencil]: [SHIFT, 'P'],
  placeImage: [SHIFT, CONTROL, 'K'],
  [ToolName.polygon]: [],
  [ToolName.rectangle]: ['R'],
  redo: [SHIFT, CONTROL, 'Z'],
  renameLayer: [CONTROL, 'R'],
  saveToVersionHistory: [ALT, CONTROL, 'S'],
  [ToolName.scale]: ['K'],
  [ToolName.section]: [SHIFT, 'S'],
  selectAll: [CONTROL, 'A'],
  selectInverse: [SHIFT, CONTROL, 'A'],
  selectMatchingLayers: [ALT, CONTROL, 'A'],
  selectNone: ['↺'],
  sendToBack: ['['],
  [ToolName.slice]: ['S'],
  [ToolName.star]: [],
  [ToolName.text]: ['T'],
  [ToolName.textOnPath]: [],
  toggleUiMinimized: [SHIFT, CONTROL, '\\'],
  undo: [CONTROL, 'Z'],
};
